### PR TITLE
Adding quotation, paraphrasing and citation for dockerhub.tex and other tutorials

### PR DESCRIPTION
**Pull request by minchen57**
Also checked three other tutorials made by me including pi-dhcp and sd-card-osx. 
Add citations to all linked resources, provide quotes and paraphrasing if necessary. 
Sorry for the issue caused, please let me know if other changes are needed for these to enter the book.

### CODE REVIEW

**Comment by laszewsk** [comment]
pull request rejected at this time as check has failed

**Comment by minchen57** [comment]
is there any info on why the check is not passed?

**Comment by laszewsk** [comment]
I am working on it. I just found a wrong refernce and corrected in the overall book. It now passes locally and i hope I checked in all files.

**Comment by minchen57** [comment]
Please let me know if I need to submit a pull request again? Actually I fixed several typos in the reference.bib just now.

**Pull request merged**
